# This file maps rpcs to their http annotations for grpc-gateway

type: google.api.Service
config_version: 3

http:
  rules:
    # Bluehenge - v2
    - selector: cobaltspeech.bluehenge.v2.BluehengeService.Version
      get: /api/bluehenge/v2/version
    - selector: cobaltspeech.bluehenge.v2.BluehengeService.ListModels
      get: /api/bluehenge/v2/list-models
    - selector: cobaltspeech.bluehenge.v2.BluehengeService.CreateSession
      post: /api/bluehenge/v2/create-session
      body: "*"
    - selector: cobaltspeech.bluehenge.v2.BluehengeService.DeleteSession
      post: /api/bluehenge/v2/delete-session
      body: "*"
    - selector: cobaltspeech.bluehenge.v2.BluehengeService.UpdateSession
      post: /api/bluehenge/v2/update-session
      body: "*"
    - selector: cobaltspeech.bluehenge.v2.BluehengeService.ListProcedures
      get: /api/bluehenge/v2/list-procedures
    - selector: cobaltspeech.bluehenge.v2.BluehengeService.ListTrees
      get: /api/bluehenge/v2/list-trees
    - selector: cobaltspeech.bluehenge.v2.BluehengeService.ListEntities
      get: /api/bluehenge/v2/list-entities
    - selector: cobaltspeech.bluehenge.v2.BluehengeService.GetProcedure
      post: /api/bluehenge/v2/get-procedure
      body: "*"
    - selector: cobaltspeech.bluehenge.v2.BluehengeService.GetTask
      post: /api/bluehenge/v2/get-task
      body: "*"
    - selector: cobaltspeech.bluehenge.v2.BluehengeService.GetEntity
      post: /api/bluehenge/v2/get-entity
      body: "*"
    - selector: cobaltspeech.bluehenge.v2.BluehengeService.SaveNote
      post: /api/bluehenge/v2/save-note
      body: "*"
    - selector: cobaltspeech.bluehenge.v2.BluehengeService.GetExtractionRelationship
      post: /api/bluehenge/v2/get-extraction-relationship
      body: "*"
    - selector: cobaltspeech.bluehenge.v2.BluehengeService.GetEntityImageData
      post: /api/bluehenge/v2/get-entity-image-data
      body: "*"

    # Chosun - v2
    - selector: cobaltspeech.chosun.v2.ChosunService.Version
      get: /api/chosun/v2/version
    - selector: cobaltspeech.chosun.v2.ChosunService.ListModels
      get: /api/chosun/v2/list-models
    - selector: cobaltspeech.chosun.v2.ChosunService.Parse
      post: /api/chosun/v2/parse
      body: "*"

    # Cubic - v1
    - selector: cobaltspeech.cubic.Cubic.Version
      get: /api/cubic/v1/version
    - selector: cobaltspeech.cubic.Cubic.ListModels
      get: /api/cubic/v1/list-models
    - selector: cobaltspeech.cubic.Cubic.Recognize
      post: /api/cubic/v1/recognize
      body: "*"
    - selector: cobaltspeech.cubic.Cubic.StreamingRecognize
      post: /api/cubic/v1/streaming-recognize
      body: "*"
    - selector: cobaltspeech.cubic.Cubic.CompileContext
      post: /api/cubic/v1/compile-context
      body: "*"

    # Cubic - v5
    - selector: cobaltspeech.cubic.v5.CubicService.Version
      get: /api/cubic/v5/version
    - selector: cobaltspeech.cubic.v5.CubicService.ListModels
      get: /api/cubic/v5/list-models
    - selector: cobaltspeech.cubic.v5.CubicService.StreamingRecognize
      post: /api/cubic/v5/streaming-recognize
      body: "*"
    - selector: cobaltspeech.cubic.v5.CubicService.CompileContext
      post: /api/cubic/v5/compile-context
      body: "*"

    # Diatheke - v3
    - selector: cobaltspeech.diatheke.v3.DiathekeService.Version
      get: /api/diatheke/v3/version
    - selector: cobaltspeech.diatheke.v3.DiathekeService.ListModels
      get: /api/diatheke/v3/list-models
    - selector: cobaltspeech.diatheke.v3.DiathekeService.CreateSession
      post: /api/diatheke/v3/create-session
      body: "*"
    - selector: cobaltspeech.diatheke.v3.DiathekeService.DeleteSession
      post: /api/diatheke/v3/delete-session
      body: "*"
    - selector: cobaltspeech.diatheke.v3.DiathekeService.UpdateSession
      post: /api/diatheke/v3/update-session
      body: "*"
    - selector: cobaltspeech.diatheke.v3.DiathekeService.StreamASR
      post: /api/diatheke/v3/stream-asr
      body: "*"
    - selector: cobaltspeech.diatheke.v3.DiathekeService.StreamASRWithPartials
      post: /api/diatheke/v3/stream-asr-with-partials
      body: "*"
    - selector: cobaltspeech.diatheke.v3.DiathekeService.Transcribe
      post: /api/diatheke/v3/transcribe
      body: "*"
    - selector: cobaltspeech.diatheke.v3.DiathekeService.StreamTTS
      post: /api/diatheke/v3/stream-tts
      body: "*"

    # Interact - v3
    - selector: cobaltspeech.interact.v3.InteractService.Version
      get: /api/diatheke/v3/version
    - selector: cobaltspeech.interact.v3.InteractService.ListModels
      get: /api/diatheke/v3/list-models
    - selector: cobaltspeech.interact.v3.InteractService.CreateSession
      post: /api/diatheke/v3/create-session
      body: "*"
    - selector: cobaltspeech.interact.v3.InteractService.DeleteSession
      post: /api/diatheke/v3/delete-session
      body: "*"
    - selector: cobaltspeech.interact.v3.InteractService.UpdateSession
      post: /api/diatheke/v3/update-session
      body: "*"
    - selector: cobaltspeech.interact.v3.InteractService.StreamASR
      post: /api/diatheke/v3/stream-asr
      body: "*"
    - selector: cobaltspeech.interact.v3.InteractService.StreamASRWithPartials
      post: /api/diatheke/v3/stream-asr-with-partials
      body: "*"
    - selector: cobaltspeech.interact.v3.InteractService.Transcribe
      post: /api/diatheke/v3/transcribe
      body: "*"
    - selector: cobaltspeech.interact.v3.InteractService.StreamTTS
      post: /api/diatheke/v3/stream-tts
      body: "*"

    # Privacyscreen - v1
    - selector: cobaltspeech.privacyscreen.v1.PrivacyScreenService.Version
      get: /api/privacyscreen/v1/version
    - selector: cobaltspeech.privacyscreen.v1.PrivacyScreenService.ListModels
      get: /api/privacyscreen/v1/list-models
    - selector: cobaltspeech.privacyscreen.v1.PrivacyScreenService.RedactText
      post: /api/privacyscreen/v1/redact-text
      body: "*"
    - selector: cobaltspeech.privacyscreen.v1.PrivacyScreenService.RedactTranscript
      post: /api/privacyscreen/v1/redact-transcript
      body: "*"
    - selector: cobaltspeech.privacyscreen.v1.PrivacyScreenService.StreamingRedactTranscribedAudio
      get: /api/privacyscreen/v1/streaming-redact-transcribed-audio
    - selector: cobaltspeech.privacyscreen.v1.PrivacyScreenService.StreamingTranscribeAndRedact
      get: /api/privacyscreen/v1/streaming-transcribe-and-redact

    # Transcribe - v5
    - selector: cobaltspeech.transcribe.v5.TranscribeService.Version
      get: /api/transcribe/v5/version
    - selector: cobaltspeech.transcribe.v5.TranscribeService.ListModels
      get: /api/transcribe/v5/list-models
    - selector: cobaltspeech.transcribe.v5.TranscribeService.StreamingRecognize
      get: /api/transcribe/v5/streaming-recognize
    - selector: cobaltspeech.transcribe.v5.TranscribeService.CompileContext
      post: /api/transcribe/v5/compile-context
      body: "*"

    # Voicebio - v1
    - selector: cobaltspeech.voicebio.v1.VoiceBioService.Version
      get: /api/voicebio/v1/version
    - selector: cobaltspeech.voicebio.v1.VoiceBioService.ListModels
      get: /api/voicebio/v1/list-models
    - selector: cobaltspeech.voicebio.v1.VoiceBioService.StreamingEnroll
      get: /api/voicebio/v1/streaming-enroll
    - selector: cobaltspeech.voicebio.v1.VoiceBioService.StreamingVerify
      get: /api/voicebio/v1/streaming-verify
    - selector: cobaltspeech.voicebio.v1.VoiceBioService.StreamingIdentify
      get: /api/voicebio/v1/streaming-identify

    # Voicegen - v1
    - selector: cobaltspeech.voicegen.v1.VoiceGenService.Version
      get: /api/voicegen/v1/version
    - selector: cobaltspeech.voicegen.v1.VoiceGenService.ListModels
      get: /api/voicegen/v1/list-models
    - selector: cobaltspeech.voicegen.v1.VoiceGenService.StreamingSynthesize
      get: /api/voicegen/v1/streaming-synthesize
