name: cache devshells

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  cache-devshells:
    uses: cobaltspeech/.github/.github/workflows/cache-nix-devshells.yml@master
